CXX=clang++-5.0
CXX_FLAGS= -std=c++17

PERMAP=persist_map
PERMAP_INT=persist_map_int


all: $(PERMAP) $(PERMAP_INT)

$(PERMAP): $(PERMAP).cpp permap.hpp
	$(CXX) $(CXX_FLAGS) $(PERMAP).cpp -o $(PERMAP)
$(PERMAP_INT): $(PERMAP_INT).cpp permap.hpp
	$(CXX) $(CXX_FLAGS) $(PERMAP_INT).cpp -o $(PERMAP_INT)
clean:
	rm -f $(PERMAP) $(PERMAP_INT)


