CXX=clang++
CXX_FLAGS=-std=c++1z

TEMP_STACK=template_stack
ARRAY_C=array_cast
FOR_E=for_each

all: $(TEMP_STACK) $(ARRAY_C) $(FOR_E)

$(FOR_E): $(FOR_E).cpp
	$(CXX) $(CXX_FLAGS) $(FOR_E).cpp -o $(FOR_E)

$(TEMP_STACK): $(TEMP_STACK).cpp
	$(CXX) $(CXX_FLAGS) $(TEMP_STACK).cpp -o $(TEMP_STACK)

$(ARRAY_C): $(ARRAY_C).cpp
	$(CXX) $(CXX_FLAGS) $(ARRAY_C).cpp -o $(ARRAY_C)
clean:
	rm -f $(TEMP_STACK) $(ARRAY_C) $(FOR_E)

