CXX=clang++-5.0
CXX_FLAGS=-std=c++17

TEMP_STACK=template_stack
ARRAY_C=array_cast

all: $(TEMP_STACK) $(ARRAY_C)


$(TEMP_STACK): $(TEMP_STACK).cpp
	$(CXX) $(CXX_FLAGS) $(TEMP_STACK).cpp -o $(TEMP_STACK)

$(ARRAY_C): $(ARRAY_C).cpp
	$(CXX) $(CXX_FLAGS) $(ARRAY_C).cpp -o $(ARRAY_C)
clean:
	rm -f $(TEMP_STACK) $(ARRAY_C)

