CXX=clang++-5.0
CXX_FLAGS= -std=c++17
TEMPLATEA=template_auto
TEMPSTACK=template_stack_auto

all: $(TEMPLATEA) $(TEMPSTACK)

$(TEMPLATEA): $(TEMPLATEA).cpp
	$(CXX) $(CXX_FLAGS) $(TEMPLATEA).cpp -o $(TEMPLATEA)

$(TEMPSTACK): $(TEMPSTACK).cpp
	$(CXX) $(CXX_FLAGS) $(TEMPSTACK).cpp -o $(TEMPSTACK)
clean:
	rm -f $(TEMPLATEA) $(TEMPSTACK)
 
