CXX_FLAGS=-std=c++1z
# change CXX to your compiler below
CXX=clang++

PROGRAM=program

all: scope $(PROGRAM)

$(PROGRAM): $(PROGRAM).cpp
	$(CXX) $(CXX_FLAGS) $(PROGRAM).cpp -o $(PROGRAM)

scope: scope.cpp
	$(CXX) $(CXX_FLAGS) scope.cpp -o scope
clean:
	rm -f scope $(PROGRAM)
